// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  logo: string;
  menu: string;
  menuLink: string;
  root: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
