// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cloud: string;
  cloudSmall: string;
  pikachu: string;
  pokeball: string;
  pokeballSmall: string;
  root: string;
}
export const cssExports: CssExports;
export default cssExports;
